### PR TITLE
Removed .venv, added requirements.txt

### PR DESCRIPTION
**Pull request by MK732**
Added requirements.txt for easier installation of dependencies.

Removed .venv from repo as it shouldn't be on github. 

For the future, if you need to install a package, do so through your venv and then run

```bash
pip freeze > requirements.txt
```
If another developer needs to fork this and easily install all dependencies, they just need to do 

```bash
pip install -r requirements.txt
```
 And it will install everything in that document.

### CODE REVIEW

**Comment by MK732** [comment]
I should've made a feature/branch, but seeing as no one has contributed yet and you are still in the early stages, I kept it in main.

**Comment by asteng88** [comment]
This is Awesome. Thanks @MK732 for the tip and I appreciate the help and advice.

**Comment by MK732** [comment]
> This is Awesome. Thanks @MK732 for the tip and I appreciate the help and advice.

Of course! It seems that the .venv folder is still on github. Usually this happens if it was already commited before the .gitignore. You can manually delete it from github to make it easier. Or keep it there, but it may affect others that try to clone if they use the same virtual env name.

**Comment by asteng88** [comment]
I will manually remove it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
